### ISSUE TITLE
create#CheckoutFromSalesOrder has unused orderPartSeqId

### ISSUE THREAD

**Issue by eigood** [coarchy/stripe#2]
https://github.com/coarchy/stripe/blob/3ea626d9b6b4eebbe47a9a0316d92fdba56d2034/service/stripe/StripeServices.xml#L24

The body of this service stores a checkoutId/checkoutUrl into the OrderPart.  This implies supporting multiple order parts, if only there was a way to specify which part to use.  The service has an orderPartSeqId parameter, but then never sets it into the query at the top of the service.

The simple fix would be to just add `<econdition field-name="orderPartSeqId"/>` to the OrderHeaderAndPart find.

**Comment by acetousk** [comment]
It is not intended to imply supporting multiple order parts. Only one order part is used in case of different payments / vendors / customers for other order parts.

This is fixed in: https://github.com/coarchy/stripe/commit/86ae8f020612029f3c6f1f642b0552e9dbde9620

**Comment by eigood** [comment]
Yeah, I figured the "serializer" for stripe only supports a single part, as that is where the special state values are saved to.  But still, external code could specify with OrderPart to sent to stripe.  This is for the case of split-ship, or some such, where each order goes to a different location, and should only be charged once each part is ready to be shipped.
