### ISSUE TITLE
Missing documentation on which webhook event types to register for

### ISSUE THREAD

**Issue by eigood** [coarchy/stripe#3]
https://github.com/coarchy/stripe/blob/3ea626d9b6b4eebbe47a9a0316d92fdba56d2034/README.md?plain=1#L24

I had to read the implementation of the service, to see that "checkout.session.completed" and "checkout.session.expired" needed to be added to the webhook configuration screen in Stripe.

**Comment by acetousk** [comment]
Should be fixed in https://github.com/coarchy/stripe/commit/7cdf9d31d5299d74899b5decbb69c8c368c916aa
