### ISSUE TITLE
Missing method flattenNestedMapWithKeys

### ISSUE THREAD

**Issue by eigood** [coarchy/stripe#5]
`groovy.lang.MissingMethodException:` No signature of method: stripe_StripeServices_create_CheckoutFromSalesOrder.flattenNestedMapWithKeys() is applicable for argument types: (LinkedHashMap) values: [[success_url:/test-success, cancel_url:/test-cancel, mode:payment, ...]]`

My moqui-framework version is f6e7025bb71c1d472846d4c6e2131199b822ca20; I also do not see that method at all in moqui-framework on github.

**Comment by acetousk** [comment]
See this commit to moqui-framework: https://github.com/moqui/moqui-framework/commit/d677e40c14e7a93b10eefed245e582ae3bad6e5d
